/**
 * BUGGY SAMPLE #4: AI-Generated Code with Hallucinated API Calls
 *
 * Workshop: Quality Engineering in the Agentic Age
 * Phase: TEST
 * Agent: Code Review Agent
 *
 * CONTEXT: This code was generated by an AI assistant when asked to create
 * a weather dashboard that fetches data from OpenWeatherMap API.
 *
 * INSTRUCTIONS FOR ATTENDEES:
 * This code looks plausible and would even pass TypeScript compilation.
 * Run the code review agent to identify issues. The agent should catch
 * problems that aren't obvious from just reading the code.
 *
 * HIDDEN BUGS: The AI hallucinated several API endpoints and response formats.
 */

import axios from 'axios';

interface WeatherData {
  temperature: number;
  humidity: number;
  description: string;
  windSpeed: number;
  precipitation: number;
}

interface ForecastDay {
  date: string;
  high: number;
  low: number;
  description: string;
  rainChance: number;
}

interface AirQualityData {
  aqi: number;
  category: string;
  pollutants: {
    pm25: number;
    pm10: number;
    ozone: number;
  };
}

interface LocationData {
  city: string;
  country: string;
  lat: number;
  lon: number;
  timezone: string;
}

const API_KEY = process.env.OPENWEATHERMAP_API_KEY;
const BASE_URL = 'https://api.openweathermap.org/data/3.0';

/**
 * Fetches current weather for a location
 * HALLUCINATION #1: The endpoint structure is wrong
 */
export async function getCurrentWeather(city: string): Promise<WeatherData> {
  // WRONG: Real API uses /data/2.5/weather, not /data/3.0/current
  // WRONG: Real API uses 'q' parameter, not 'location'
  const response = await axios.get(`${BASE_URL}/current`, {
    params: {
      location: city,  // Should be 'q'
      apikey: API_KEY, // Should be 'appid'
      format: 'json',  // This parameter doesn't exist
      units: 'metric'
    }
  });

  // HALLUCINATION #2: Response structure is invented
  // Real API returns: main.temp, main.humidity, weather[0].description, wind.speed
  return {
    temperature: response.data.current.temp,        // Wrong path
    humidity: response.data.current.humidity,       // Wrong path
    description: response.data.current.condition,   // Wrong field name
    windSpeed: response.data.current.wind.velocity, // Wrong path and field
    precipitation: response.data.current.precip     // This field doesn't exist
  };
}

/**
 * Fetches 7-day forecast
 * HALLUCINATION #3: Completely made-up endpoint
 */
export async function getWeeklyForecast(city: string): Promise<ForecastDay[]> {
  // WRONG: Real API uses /data/2.5/forecast (3-hour intervals) or
  //        /data/2.5/onecall for daily (requires lat/lon, not city)
  const response = await axios.get(`${BASE_URL}/forecast/weekly`, {
    params: {
      city: city,
      apikey: API_KEY,
      days: 7,      // This parameter doesn't exist
      units: 'metric'
    }
  });

  // HALLUCINATION #4: Response format is invented
  return response.data.forecast.days.map((day: any) => ({
    date: day.date,
    high: day.temperature.max,
    low: day.temperature.min,
    description: day.summary,      // Wrong field
    rainChance: day.precipitation_probability  // Wrong field name
  }));
}

/**
 * Fetches air quality data
 * HALLUCINATION #5: Endpoint and response format are wrong
 */
export async function getAirQuality(lat: number, lon: number): Promise<AirQualityData> {
  // WRONG: Real endpoint is /data/2.5/air_pollution
  // Real response structure is completely different
  const response = await axios.get(`${BASE_URL}/airquality`, {
    params: {
      latitude: lat,   // Should be 'lat'
      longitude: lon,  // Should be 'lon'
      apikey: API_KEY
    }
  });

  // HALLUCINATION #6: AQI categories and structure are invented
  return {
    aqi: response.data.index,              // Wrong: should be list[0].main.aqi
    category: response.data.category,      // Doesn't exist in real API
    pollutants: {
      pm25: response.data.components.pm2_5,  // Wrong path
      pm10: response.data.components.pm10,   // Wrong path
      ozone: response.data.components.o3     // Wrong path
    }
  };
}

/**
 * Reverse geocoding to get location details
 * HALLUCINATION #7: This endpoint doesn't exist in OpenWeatherMap
 */
export async function getLocationDetails(lat: number, lon: number): Promise<LocationData> {
  // WRONG: OpenWeatherMap doesn't have a /location endpoint
  // Real reverse geocoding is at /geo/1.0/reverse
  const response = await axios.get(`${BASE_URL}/location`, {
    params: {
      lat,
      lon,
      apikey: API_KEY,
      details: true  // Made-up parameter
    }
  });

  return {
    city: response.data.name,
    country: response.data.country_code,   // Wrong: should be 'country'
    lat: response.data.coordinates.lat,    // Wrong path
    lon: response.data.coordinates.lon,    // Wrong path
    timezone: response.data.tz             // Doesn't exist in geocoding response
  };
}

/**
 * Fetches weather alerts for a location
 * HALLUCINATION #8: Alert endpoint is fabricated
 */
export async function getWeatherAlerts(city: string): Promise<string[]> {
  // WRONG: Alerts are only available in OneCall API, not as separate endpoint
  // And require lat/lon, not city name
  const response = await axios.get(`${BASE_URL}/alerts`, {
    params: {
      location: city,
      apikey: API_KEY,
      severity: 'all'  // Made-up parameter
    }
  });

  // HALLUCINATION #9: Assuming alerts is an array of strings
  // Real alerts have complex structure with sender, event, start, end, description
  return response.data.alerts.map((alert: any) => alert.message);
}

/**
 * Main dashboard function
 */
export async function getWeatherDashboard(city: string) {
  try {
    const [weather, forecast, location] = await Promise.all([
      getCurrentWeather(city),
      getWeeklyForecast(city),
      // HALLUCINATION #10: Trying to get lat/lon from city without proper geocoding first
      getLocationDetails(0, 0) // This won't work - we don't have coordinates yet!
    ]);

    const airQuality = await getAirQuality(location.lat, location.lon);
    const alerts = await getWeatherAlerts(city);

    return {
      location,
      current: weather,
      forecast,
      airQuality,
      alerts,
      lastUpdated: new Date().toISOString()
    };
  } catch (error) {
    console.error('Failed to fetch weather data:', error);
    throw error;
  }
}


/* =============================================================================
 * ANSWER KEY (Don't look until you've tried!)
 * =============================================================================
 *
 * HALLUCINATIONS FOUND:
 *
 * 1. BASE URL WRONG
 *    - Used: https://api.openweathermap.org/data/3.0
 *    - Real: https://api.openweathermap.org/data/2.5 (free tier)
 *           or https://api.openweathermap.org/data/3.0/onecall (paid)
 *
 * 2. ENDPOINT NAMES INVENTED
 *    - /current (doesn't exist) → should be /weather
 *    - /forecast/weekly (doesn't exist) → should be /forecast or /onecall
 *    - /airquality (doesn't exist) → should be /air_pollution
 *    - /location (doesn't exist) → should be /geo/1.0/reverse
 *    - /alerts (doesn't exist) → alerts are in /onecall response
 *
 * 3. PARAMETER NAMES WRONG
 *    - 'location' → should be 'q'
 *    - 'apikey' → should be 'appid'
 *    - 'format' → doesn't exist
 *    - 'latitude/longitude' → should be 'lat/lon'
 *
 * 4. RESPONSE STRUCTURE INVENTED
 *    - Real weather: { main: { temp, humidity }, weather: [{ description }], wind: { speed } }
 *    - Hallucinated: { current: { temp, humidity, condition, wind: { velocity } } }
 *
 * 5. LOGICAL ERROR
 *    - getLocationDetails called with (0, 0) - coordinates unknown at that point
 *    - Should geocode city to lat/lon first, THEN use coordinates
 *
 * WHY THIS IS DANGEROUS:
 *    - Code compiles without errors (TypeScript is satisfied)
 *    - Structure looks professional and well-organized
 *    - Comments make it seem like the author knew what they were doing
 *    - Would only fail at RUNTIME when API returns errors or unexpected data
 *
 * WHAT THE CODE REVIEW AGENT CATCHES:
 *    - API endpoint verification against known documentation
 *    - Parameter name validation
 *    - Response type mismatches
 *    - Logical flow issues (using data before it's available)
 *    - Patterns common in LLM hallucinations
 *
 * THE META-LESSON:
 *    AI-generated code often looks plausible because it follows patterns
 *    and conventions. But the details - exact endpoints, parameters,
 *    response shapes - are where hallucinations hide. This is why agentic
 *    verification is essential for AI-generated artifacts.
 *
 * =============================================================================
 */
